
[font]
size = 14.0

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
# family = "SFMono Nerd Font"
family = "Cousine Nerd Font"
style = "Regular"


[window]
# decorations = "buttonless"
dynamic_padding = false
#opacity = 0.5

[window.padding]
x = 14
y = 12

[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/gruvbox_material_medium_dark.toml"
#	 "~/.config/alacritty/themes/gruber_darker.toml"
]

[[keyboard.bindings]]
key = "1"
mods = "Control"
chars = "\uE001"

[[keyboard.bindings]]
key = "2"
mods = "Control"
chars = "\uE002"

[[keyboard.bindings]]
key = "3"
mods = "Control"
chars = "\uE003"

[[keyboard.bindings]]
key = "4"
mods = "Control"
chars = "\uE004"

[[keyboard.bindings]]
key = "5"
mods = "Control"
chars = "\uE005"

[[keyboard.bindings]]
key = "6"
mods = "Control"
chars = "\uE006"

[[keyboard.bindings]]
key = "7"
mods = "Control"
chars = "\uE007"

[[keyboard.bindings]]
key = "8"
mods = "Control"
chars = "\uE008"

[[keyboard.bindings]]
key = "9"
mods = "Control"
chars = "\uE009"

[[keyboard.bindings]]
key = "k"
mods = "Control"
chars = "\uE010"
