
[font]
size = 14.0

[font.normal]
# family = "SFMono Nerd Font"
family = "Cousine Nerd Font"
style = "Regular"


[window]
decorations = "buttonless"
dynamic_padding = false
#opacity = 0.5

[window.padding]
x = 14
y = 12

[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/gruvbox_material_medium_dark.toml"
#	 "~/.config/alacritty/themes/gruber_darker.toml"


]
